[package]
name = "rust-kernel-project"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.7"

[dependencies.core]
optional = true

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
